/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sanctum/csrf-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Web. Initialise la protection CSRF (pose le cookie XSRF-TOKEN) */
        get: operations["csrfCookie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Web. Redirige vers GitHub (dépôts publics uniquement, jamais la permission repo). Connecté : lie GitHub au compte existant. */
        get: operations["githubRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retour de GitHub, ouvre la session */
        get: operations["githubCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/lien-magique": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Web. Envoie un lien de connexion par email (clients sans GitHub) */
        post: operations["demanderLienMagique"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/lien-magique/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Web. Lien reçu par email, à usage unique et limité dans le temps ; ouvre la session */
        get: operations["utiliserLienMagique"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Web. Ferme la session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/broadcasting/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Web. Autorise l'écoute d'un canal privé Reverb (appelé par Laravel Echo) */
        post: operations["broadcastingAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mon compte */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifier mon profil (pays, bio) ; seuls les champs envoyés sont modifiés */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/devs/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil public (dépôts, étoiles, README) */
        get: operations["getDev"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Le store */
        get: operations["listApps"];
        put?: never;
        /** Publier une appli (GitHub lié obligatoire ; soukdev.json validé immédiatement avec soukdev.schema.json ; captures envoyées dans le même formulaire ; refusée en 422 si un secret ou un docker-compose.yml dangereux est trouvé ; l'analyse des dépendances démarre ensuite) */
        post: operations["createApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vérifier un dépôt avant de publier (dépôt public, docker-compose.yml, soukdev.json validé, aucun secret, docker-compose.yml sans réglage dangereux) ; ne publie rien */
        post: operations["verifyAppRepo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Détail d'une appli (README, démo, prix, auteur) */
        get: operations["getApp"];
        put?: never;
        post?: never;
        /** Retirer une appli (auteur uniquement) */
        delete: operations["deleteApp"];
        options?: never;
        head?: never;
        /** Modifier une appli (auteur uniquement) */
        patch: operations["updateApp"];
        trace?: never;
    };
    "/apps/{id}/captures": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remplacer toutes les captures d'une appli (auteur uniquement ; POST car PHP ne lit pas le multipart en PATCH) */
        post: operations["replaceAppCaptures"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{id}/securite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Relancer l'analyse de sécurité (auteur uniquement), par exemple après avoir corrigé une dépendance */
        post: operations["rescanAppSecurity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste fixe des catégories d'appli (type de projet) */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/technos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste fixe des technos (stack d'une appli, filtre du store) */
        get: operations["listTechnos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{id}/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lancer un déploiement client (répond tout de suite avec l'état en_file). Paiement du serveur : mécanisme en attente (voir DECISIONS.md). */
        post: operations["createDeployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mes déploiements */
        get: operations["listDeployments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** État et URL d'un déploiement */
        get: operations["getDeployment"];
        put?: never;
        post?: never;
        /** Arrêter un déploiement */
        delete: operations["deleteDeployment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discussions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Le fil (filtrable par appli, canal ou étiquette) */
        get: operations["listDiscussions"];
        put?: never;
        /** Poster une discussion (appli jointe en option) */
        post: operations["createDiscussion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discussions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Une discussion (ses messages : GET /discussions/{id}/messages) */
        get: operations["getDiscussion"];
        put?: never;
        post?: never;
        /** Supprimer une discussion (auteur ou admin) */
        delete: operations["deleteDiscussion"];
        options?: never;
        head?: never;
        /** Modifier sa discussion (auteur uniquement) */
        patch: operations["updateDiscussion"];
        trace?: never;
    };
    "/discussions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Messages d'une discussion, du plus ancien au plus récent */
        get: operations["listMessages"];
        put?: never;
        /** Répondre dans une discussion */
        post: operations["createMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discussions/{id}/copie-test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lancer une copie de test, sur demande explicite de l'auteur (à partir du depot_url ou de l'appli jointe ; soukdev.json requis) */
        post: operations["createCopieTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Supprimer un message (auteur ou admin) */
        delete: operations["deleteMessage"];
        options?: never;
        head?: never;
        /** Modifier son message (auteur uniquement) */
        patch: operations["updateMessage"];
        trace?: never;
    };
    "/canaux": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des canaux */
        get: operations["listCanaux"];
        put?: never;
        /** Créer un canal */
        post: operations["createCanal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/etiquettes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste fixe des étiquettes de sujet */
        get: operations["listEtiquettes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discussions/{id}/correctifs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Correctifs proposés pour une discussion */
        get: operations["listCorrectifs"];
        put?: never;
        /** Proposer un correctif : URL d'une branche ou d'un fork GitHub (GitHub lié obligatoire). Aucun déploiement automatique. */
        post: operations["createCorrectif"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/correctifs/{id}/accepter": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accepter un correctif (auteur de la discussion ; un seul accepté par discussion ; marque la discussion résolue ; ne fusionne rien sur GitHub) */
        post: operations["acceptCorrectif"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/correctifs/{id}/deploiement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optionnel. Déployer sa version corrigée pour la montrer tourner (auteur du correctif ; soukdev.json requis) */
        post: operations["deployCorrectif"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{id}/missions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demander une version sur mesure à l'auteur de l'appli (privé, sans enchères) */
        post: operations["createMission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mes missions, comme client ou comme auteur */
        get: operations["listMissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Une mission (client ou auteur uniquement) */
        get: operations["getMission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Fil privé de la mission (client ou auteur uniquement) */
        get: operations["listMissionMessages"];
        put?: never;
        /** Écrire dans le fil privé de la mission */
        post: operations["createMissionMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste des événements */
        get: operations["listEvents"];
        put?: never;
        /** Créer un événement */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Détail d'un événement (lien en ligne visible par les inscrits uniquement) */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        /** Supprimer un événement (organisateur ou admin) ; les inscrits sont prévenus */
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        /** Modifier un événement (organisateur uniquement) */
        patch: operations["updateEvent"];
        trace?: never;
    };
    "/events/{id}/inscription": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** S'inscrire */
        post: operations["registerEvent"];
        /** Se désinscrire */
        delete: operations["unregisterEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Liste des participants (inscrits et organisateur uniquement ; le nombre d'inscrits est public) */
        get: operations["listParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}/avis": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Avis laissés sur un événement */
        get: operations["listAvis"];
        put?: never;
        /** Laisser un avis (inscrit uniquement, après la date, un seul par dev) */
        post: operations["createAvis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Erreur: {
            message: string;
        };
        ErreurValidation: {
            message: string;
            /** @description Erreurs par champ (format de validation Laravel) */
            errors: {
                [key: string]: string[];
            };
        };
        /** @description Format de pagination des API Resources Laravel ; la liste est dans data */
        Pagination: {
            links: {
                /** Format: uri */
                first: string | null;
                /** Format: uri */
                last: string | null;
                /** Format: uri */
                prev: string | null;
                /** Format: uri */
                next: string | null;
            };
            meta: {
                current_page: number;
                last_page: number;
                per_page: number;
                total: number;
            };
        };
        /** @description Un compte tel qu'il apparaît publiquement (auteur, participant, client d'une mission…) */
        Dev: {
            id: number;
            nom: string | null;
            /** @description Facultatif ; null tant que la personne ne l'a pas choisi */
            pays: components["schemas"]["Pays"] | null;
            /** @description Identifiant GitHub ; null si GitHub non lié */
            username: string | null;
            /** Format: uri */
            avatar_url: string | null;
            /** Format: uri */
            github_url: string | null;
            /**
             * @description Choix d'entrée, sert à la redirection ; pas une étiquette définitive
             * @enum {string}
             */
            profil: "dev" | "client";
        };
        /** @description Code pays ISO 3166-1 alpha-2, ex. BJ (Bénin), SN (Sénégal), CI (Côte d'Ivoire). Tous les pays sont acceptés. */
        Pays: string;
        /** @description Tous les champs sont optionnels ; null efface la valeur */
        CompteModification: {
            pays?: components["schemas"]["Pays"] | null;
            bio?: string | null;
        };
        /** @description Mon compte (GET /me) */
        Compte: components["schemas"]["Dev"] & {
            /** Format: email */
            email: string | null;
            /** @description Obligatoire pour publier une appli ou proposer un correctif */
            github_lie: boolean;
            est_admin: boolean;
        };
        LienMagiqueDemande: {
            /** Format: email */
            email: string;
        };
        /** @description Profil public d'un dev, avec ses dépôts publics GitHub et ses applis publiées */
        ProfilDev: components["schemas"]["Dev"] & {
            bio?: string | null;
            depots: components["schemas"]["Depot"][];
            applis: components["schemas"]["App"][];
        };
        /** @description Dépôt public GitHub du dev */
        Depot: {
            nom: string;
            description?: string | null;
            /** Format: uri */
            url: string;
            etoiles: number;
            langage?: string | null;
            /** @description README en Markdown */
            readme?: string | null;
        };
        App: {
            id: number;
            nom: string;
            description: string;
            /** @description README du dépôt en Markdown */
            readme?: string | null;
            categorie: components["schemas"]["Categorie"];
            /** @description Prix de l'appli en FCFA */
            prix: number;
            type_prix: components["schemas"]["TypePrix"];
            /** Format: uri */
            demo_url: string;
            /** Format: uri */
            depot_url: string;
            /** @description Captures d'écran ; la première sert de couverture sur la carte du store */
            captures: components["schemas"]["Capture"][];
            stack: components["schemas"]["Techno"][];
            /**
             * @description Type de backend déclaré dans soukdev.json
             * @enum {string}
             */
            backend: "propre" | "integre";
            /** @description Variables que le client remplit au déploiement (déclarées dans soukdev.json) */
            variables_client: components["schemas"]["VariableClient"][];
            securite: components["schemas"]["Securite"];
            auteur: components["schemas"]["Dev"];
            /** Format: date-time */
            cree_le: string;
        };
        VariableClient: {
            /** @description Nom de la variable, ex. PHARMACIE_NOM */
            nom: string;
            /** @description Texte affiché au client, ex. « Nom de la pharmacie » */
            libelle: string;
            requis: boolean;
        };
        /** @description Envoyé en multipart/form-data (champs texte + images) */
        AppCreation: {
            nom: string;
            description: string;
            /**
             * Format: uri
             * @description Dépôt GitHub public contenant docker-compose.yml et soukdev.json
             */
            depot_url: string;
            /** Format: uri */
            demo_url: string;
            categorie: components["schemas"]["Categorie"];
            prix: number;
            type_prix: components["schemas"]["TypePrix"];
            stack: components["schemas"]["Techno"][];
            captures: components["schemas"]["CapturesEnvoi"];
        };
        /**
         * @description Type de projet, choisi à la publication ; liste fixe (GET /categories)
         * @enum {string}
         */
        Categorie: "commerce" | "gestion" | "education" | "sante" | "finance" | "association" | "restauration" | "autre";
        /**
         * @description mensuel = le client paie le prix chaque mois ; unique = il le paie une seule fois. L'hébergement reste mensuel dans les deux cas. Ignoré quand prix vaut 0.
         * @enum {string}
         */
        TypePrix: "mensuel" | "unique";
        /** @description Analyse des dépendances du dépôt (Trivy). Secrets et docker-compose.yml dangereux bloquent la publication et n'apparaissent donc jamais ici. */
        Securite: {
            /**
             * @description verifie = badge vert « Security Checked » ; problemes = badge orange « Problèmes détectés »
             * @enum {string}
             */
            statut: "en_cours" | "verifie" | "problemes";
            /**
             * Format: date-time
             * @description null tant que la première analyse n'est pas finie
             */
            analyse_le: string | null;
            problemes: components["schemas"]["ProblemeSecurite"][];
        };
        /** @description Une dépendance avec une faille connue */
        ProblemeSecurite: {
            /** @description Référence publique de la faille, ex. CVE-2024-12345 */
            identifiant: string;
            /** @description ex. laravel/framework */
            paquet: string;
            /** @description Version utilisée par le dépôt */
            version: string;
            /** @enum {string} */
            gravite: "faible" | "moyenne" | "haute" | "critique";
            /** @description Première version sans la faille */
            version_corrigee: string | null;
        };
        /** @description Dépôt valide. En cas d'erreur (dépôt privé ou introuvable, docker-compose.yml absent, soukdev.json invalide, secret trouvé dans le dépôt, docker-compose.yml dangereux : privileged, volumes de l'hôte, network_mode host, ports publiés), réponse 422 avec le détail par champ. */
        VerificationDepot: {
            service_web: {
                nom: string;
                port: number;
            };
            /** @enum {string} */
            backend: "propre" | "integre";
            variables_client: components["schemas"]["VariableClient"][];
        };
        /** @description 1 à 5 images PNG, JPEG ou WebP, 5 Mo maximum chacune ; la première sert de couverture */
        CapturesEnvoi: string[];
        Capture: {
            /** Format: uri */
            url: string;
        };
        /**
         * @description Liste fixe ; « autre » pour une techno absente de la liste
         * @enum {string}
         */
        Techno: "laravel" | "symfony" | "php" | "node" | "express" | "nestjs" | "nextjs" | "react" | "vue" | "angular" | "svelte" | "django" | "flask" | "fastapi" | "spring" | "dotnet" | "go" | "postgresql" | "mysql" | "mongodb" | "redis" | "autre";
        /** @description Tous les champs sont optionnels ; seuls ceux envoyés sont modifiés */
        AppModification: {
            nom?: string;
            description?: string;
            /** Format: uri */
            demo_url?: string;
            categorie?: components["schemas"]["Categorie"];
            prix?: number;
            type_prix?: components["schemas"]["TypePrix"];
            stack?: components["schemas"]["Techno"][];
        };
        Deploiement: {
            id: number;
            app_id: number;
            /**
             * @description Copie d'un client, copie de test d'une discussion, ou version corrigée
             * @enum {string}
             */
            type: "client" | "test" | "correctif";
            /** @enum {string} */
            etat: "en_file" | "construction" | "demarrage" | "en_ligne" | "echec" | "arrete";
            /**
             * Format: uri
             * @description Renseignée quand l'état est en_ligne
             */
            url: string | null;
            /** @description Message lisible quand l'état est echec */
            erreur: string | null;
            /** Format: date-time */
            cree_le: string;
        };
        DeploiementCreation: {
            /** @description Valeurs des variables_client de l'appli, ex. {"PHARMACIE_NOM": "Pharmacie du Port"} */
            variables: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        Etiquette: "bug" | "question" | "tuto" | "projet" | "entraide";
        /** @description Une discussion est soit dans un canal, soit sur la page d'une appli, jamais les deux. */
        Discussion: {
            id: number;
            titre: string;
            /** @description Markdown */
            texte: string;
            auteur: components["schemas"]["Dev"];
            /** @description Slug du canal */
            canal: string | null;
            /** @description Appli jointe */
            app_id: number | null;
            /**
             * Format: uri
             * @description Dépôt GitHub public joint (même non publié)
             */
            depot_url: string | null;
            /**
             * Format: uri
             * @description Appli déployée ailleurs (ex. Vercel), affichée dans une iframe sandbox
             */
            demo_url: string | null;
            etiquettes: components["schemas"]["Etiquette"][];
            /** @description Rempli seulement quand la discussion porte l'étiquette bug */
            bug: components["schemas"]["Bug"] | null;
            /** @description Copie de test, seulement si l'auteur l'a lancée (POST /discussions/{id}/copie-test) */
            copie_test: components["schemas"]["Deploiement"] | null;
            /** @description Vraie quand l'auteur accepte un correctif ou la marque résolue lui-même (PATCH) */
            resolue: boolean;
            nb_messages: number;
            /** Format: date-time */
            cree_le: string;
        };
        /** @description Il faut soit canal, soit app_id (jamais les deux). depot_url et demo_url sont optionnels et ne lancent aucun déploiement. */
        DiscussionCreation: {
            titre: string;
            texte: string;
            /** @description Slug du canal ; obligatoire sans app_id */
            canal?: string;
            /** @description Appli publiée ; exclut canal */
            app_id?: number;
            /** Format: uri */
            depot_url?: string;
            /** Format: uri */
            demo_url?: string;
            etiquettes?: components["schemas"]["Etiquette"][];
            bug?: components["schemas"]["BugSaisie"];
        } & (unknown | unknown);
        /** @description Tous les champs sont optionnels ; seuls ceux envoyés sont modifiés */
        DiscussionModification: {
            titre?: string;
            texte?: string;
            /** Format: uri */
            depot_url?: string | null;
            /** Format: uri */
            demo_url?: string | null;
            etiquettes?: components["schemas"]["Etiquette"][];
            /** @description L'auteur la marque résolue (même sans correctif) ou la rouvre */
            resolue?: boolean;
            bug?: components["schemas"]["BugSaisie"];
        };
        /** @description Fiche structurée d'un bug, remplie par l'auteur de la discussion */
        Bug: {
            /** @description Ce qui se passe, ex. « le callback renvoie 500 » */
            erreur_obtenue: string;
            /** @description Ce qui devrait se passer, ex. « la commande passe en payée » */
            comportement_attendu: string;
            techno: components["schemas"]["Techno"] | null;
            /** @description Extrait de code concerné (Markdown) */
            code: string | null;
            difficulte: components["schemas"]["Difficulte"] | null;
        };
        /** @description Obligatoire à la création quand etiquettes contient bug */
        BugSaisie: {
            erreur_obtenue: string;
            comportement_attendu: string;
            techno?: components["schemas"]["Techno"];
            code?: string;
            difficulte?: components["schemas"]["Difficulte"];
        };
        /**
         * @description Choisie par l'auteur du bug
         * @enum {string}
         */
        Difficulte: "facile" | "moyen" | "difficile";
        Message: {
            id: number;
            /** @description Markdown */
            texte: string;
            auteur: components["schemas"]["Dev"];
            /** Format: date-time */
            cree_le: string;
        };
        MessageCreation: {
            texte: string;
        };
        Canal: {
            /** @description ex. laravel, mobile-money, laravel-benin */
            slug: string;
            nom: string;
            description: string | null;
            /** @description Canal d'un pays (ex. #laravel-benin → BJ) ; null pour un canal général ou régional */
            pays: components["schemas"]["Pays"] | null;
        };
        CanalCreation: {
            nom: string;
            description?: string;
            pays?: components["schemas"]["Pays"];
        };
        Correctif: {
            id: number;
            discussion_id: number;
            /**
             * Format: uri
             * @description Fork ou branche GitHub
             */
            depot_url: string;
            /**
             * Format: uri
             * @description Version corrigée déployée ailleurs (optionnel)
             */
            demo_url: string | null;
            /** @description Ce que le correctif change */
            description: string | null;
            accepte: boolean;
            /** @description Déploiement de la version corrigée, seulement si son auteur l'a lancé */
            deploiement: components["schemas"]["Deploiement"] | null;
            auteur: components["schemas"]["Dev"];
            /** Format: date-time */
            cree_le: string;
        };
        CorrectifCreation: {
            /**
             * Format: uri
             * @description URL d'une branche ou d'un fork GitHub
             */
            depot_url: string;
            description?: string;
            /** Format: uri */
            demo_url?: string;
        };
        /** @description Demande privée d'un client à l'auteur d'une appli ; visible par eux seuls */
        Mission: {
            id: number;
            app_id: number;
            client: components["schemas"]["Dev"];
            auteur: components["schemas"]["Dev"];
            /** @description Besoin exprimé par le client */
            message: string;
            /** @description Budget indicatif en FCFA */
            budget: number | null;
            /**
             * Format: date
             * @description Date souhaitée
             */
            delai: string | null;
            /** Format: date-time */
            cree_le: string;
        };
        MissionCreation: {
            message: string;
            budget?: number;
            /** Format: date */
            delai?: string;
        };
        Evenement: {
            id: number;
            titre: string;
            description: string;
            /** Format: date-time */
            date: string;
            /** @enum {string} */
            type: "en_ligne" | "presentiel";
            /** @description Renseigné si presentiel */
            lieu: string | null;
            /**
             * Format: uri
             * @description Renseigné si en_ligne ; null si le dev connecté n'est pas inscrit
             */
            lien: string | null;
            organisateur: components["schemas"]["Dev"];
            /** @description Public */
            nb_inscrits: number;
            /** @description Le dev connecté est-il inscrit ? */
            inscrit: boolean;
            /** @description null tant qu'il n'y a aucun avis */
            note_moyenne: number | null;
        };
        /** @description lieu est obligatoire si type = presentiel, lien est obligatoire si type = en_ligne */
        EvenementCreation: {
            titre: string;
            description: string;
            /** Format: date-time */
            date: string;
            /** @enum {string} */
            type: "en_ligne" | "presentiel";
            lieu?: string;
            /** Format: uri */
            lien?: string;
        };
        /** @description Tous les champs sont optionnels ; seuls ceux envoyés sont modifiés */
        EvenementModification: {
            titre?: string;
            description?: string;
            /** Format: date-time */
            date?: string;
            /** @enum {string} */
            type?: "en_ligne" | "presentiel";
            lieu?: string;
            /** Format: uri */
            lien?: string;
        };
        Avis: {
            id: number;
            note: number;
            commentaire: string | null;
            auteur: components["schemas"]["Dev"];
            /** Format: date-time */
            cree_le: string;
        };
        AvisCreation: {
            note: number;
            commentaire?: string;
        };
    };
    responses: {
        /** @description Non connecté */
        NonConnecte: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erreur"];
            };
        };
        /** @description Action non autorisée */
        Interdit: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erreur"];
            };
        };
        /** @description Ressource introuvable */
        Introuvable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erreur"];
            };
        };
        /** @description Données invalides (ex. soukdev.json invalide) */
        Invalide: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErreurValidation"];
            };
        };
        /** @description Doublon ou état incompatible (ex. deuxième avis, deuxième inscription, correctif déjà accepté) */
        Conflit: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erreur"];
            };
        };
        /** @description Jeton CSRF absent ou expiré (appeler GET /sanctum/csrf-cookie) */
        CsrfInvalide: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erreur"];
            };
        };
        /** @description Limite de débit atteinte */
        TropDeRequetes: {
            headers: {
                /** @description Secondes à attendre avant de réessayer */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erreur"];
            };
        };
    };
    parameters: {
        Id: number;
        /** @description Numéro de page (commence à 1) */
        Page: number;
        /** @description Éléments par page (50 maximum) */
        ParPage: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    csrfCookie: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cookie XSRF-TOKEN posé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    githubRedirect: {
        parameters: {
            query?: {
                /** @description Choix d'entrée, utilisé à la création du compte pour la redirection */
                profil?: "dev" | "client";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirection vers GitHub */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    githubCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ouverte, redirection vers le front */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    demanderLienMagique: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LienMagiqueDemande"];
            };
        };
        responses: {
            /** @description Email envoyé si l'adresse est valide (même réponse que le compte existe ou non) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
            429: components["responses"]["TropDeRequetes"];
        };
    };
    utiliserLienMagique: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ouverte, redirection vers le front (Store pour un client) */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lien expiré ou déjà utilisé */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Déconnecté */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            419: components["responses"]["CsrfInvalide"];
        };
    };
    broadcastingAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    socket_id: string;
                    /** @description ex. private-deploiement.12 */
                    channel_name: string;
                };
            };
        };
        responses: {
            /** @description Signature d'autorisation pour le canal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        auth: string;
                    };
                };
            };
            403: components["responses"]["Interdit"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mon compte */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Compte"];
                };
            };
            401: components["responses"]["NonConnecte"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompteModification"];
            };
        };
        responses: {
            /** @description Profil modifié */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Compte"];
                };
            };
            401: components["responses"]["NonConnecte"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
        };
    };
    getDev: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil public */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilDev"];
                };
            };
            404: components["responses"]["Introuvable"];
        };
    };
    listApps: {
        parameters: {
            query?: {
                /** @description Numéro de page (commence à 1) */
                page?: components["parameters"]["Page"];
                /** @description Éléments par page (50 maximum) */
                per_page?: components["parameters"]["ParPage"];
                /** @description Recherche dans le nom et la description */
                q?: string;
                /** @description true = uniquement les applis gratuites */
                gratuit?: boolean;
                /** @description Uniquement les applis dont la stack contient cette techno */
                techno?: components["schemas"]["Techno"];
                /** @description true = uniquement les applis au badge « Security Checked » (statut verifie) */
                securite?: boolean;
                categorie?: components["schemas"]["Categorie"];
                /** @description Pays de l'auteur */
                pays?: components["schemas"]["Pays"];
                /** @description Prix maximum en FCFA (les applis gratuites sont incluses) */
                prix_max?: number;
                type_prix?: components["schemas"]["TypePrix"];
                /** @description Par défaut, les plus récentes d'abord */
                tri?: "recent" | "prix_croissant" | "prix_decroissant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des applis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data: components["schemas"]["App"][];
                    };
                };
            };
        };
    };
    createApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AppCreation"];
            };
        };
        responses: {
            /** @description Appli publiée */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            401: components["responses"]["NonConnecte"];
            /** @description GitHub non lié au compte (obligatoire pour publier) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erreur"];
                };
            };
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
        };
    };
    verifyAppRepo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    depot_url: string;
                };
            };
        };
        responses: {
            /** @description Dépôt valide ; ce que la plateforme a lu dans soukdev.json */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationDepot"];
                };
            };
            401: components["responses"]["NonConnecte"];
            /** @description GitHub non lié au compte */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erreur"];
                };
            };
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
            429: components["responses"]["TropDeRequetes"];
        };
    };
    getApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description L'appli */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            404: components["responses"]["Introuvable"];
        };
    };
    deleteApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Appli retirée */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
        };
    };
    updateApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppModification"];
            };
        };
        responses: {
            /** @description Appli modifiée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
        };
    };
    replaceAppCaptures: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    captures: components["schemas"]["CapturesEnvoi"];
                };
            };
        };
        responses: {
            /** @description Captures remplacées */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
        };
    };
    rescanAppSecurity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analyse mise en file ; le statut passe à en_cours */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Securite"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
            429: components["responses"]["TropDeRequetes"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Les catégories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Categorie"][];
                };
            };
        };
    };
    listTechnos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Les technos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Techno"][];
                };
            };
        };
    };
    createDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeploiementCreation"];
            };
        };
        responses: {
            /** @description Déploiement mis en file ; les changements d'état arrivent par Reverb */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deploiement"];
                };
            };
            401: components["responses"]["NonConnecte"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
            429: components["responses"]["TropDeRequetes"];
        };
    };
    listDeployments: {
        parameters: {
            query?: {
                /** @description Numéro de page (commence à 1) */
                page?: components["parameters"]["Page"];
                /** @description Éléments par page (50 maximum) */
                per_page?: components["parameters"]["ParPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste de mes déploiements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data: components["schemas"]["Deploiement"][];
                    };
                };
            };
            401: components["responses"]["NonConnecte"];
        };
    };
    getDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le déploiement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deploiement"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
        };
    };
    deleteDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Déploiement arrêté */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
        };
    };
    listDiscussions: {
        parameters: {
            query?: {
                /** @description Numéro de page (commence à 1) */
                page?: components["parameters"]["Page"];
                /** @description Éléments par page (50 maximum) */
                per_page?: components["parameters"]["ParPage"];
                app?: number;
                canal?: string;
                etiquette?: components["schemas"]["Etiquette"];
                /** @description Sans ce filtre, toutes les discussions */
                statut?: "ouvertes" | "resolues";
                /** @description Uniquement les bugs de cette difficulté */
                difficulte?: components["schemas"]["Difficulte"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des discussions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data: components["schemas"]["Discussion"][];
                    };
                };
            };
        };
    };
    createDiscussion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscussionCreation"];
            };
        };
        responses: {
            /** @description Discussion créée */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Discussion"];
                };
            };
            401: components["responses"]["NonConnecte"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
            429: components["responses"]["TropDeRequetes"];
        };
    };
    getDiscussion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La discussion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Discussion"];
                };
            };
            404: components["responses"]["Introuvable"];
        };
    };
    deleteDiscussion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discussion supprimée */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
        };
    };
    updateDiscussion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscussionModification"];
            };
        };
        responses: {
            /** @description Discussion modifiée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Discussion"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description Numéro de page (commence à 1) */
                page?: components["parameters"]["Page"];
                /** @description Éléments par page (50 maximum) */
                per_page?: components["parameters"]["ParPage"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data: components["schemas"]["Message"][];
                    };
                };
            };
            404: components["responses"]["Introuvable"];
        };
    };
    createMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreation"];
            };
        };
        responses: {
            /** @description Message publié (diffusé par Reverb) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            401: components["responses"]["NonConnecte"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
        };
    };
    createCopieTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Copie de test mise en file ; son état arrive par Reverb */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deploiement"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["Conflit"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
            429: components["responses"]["TropDeRequetes"];
        };
    };
    deleteMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
        };
    };
    updateMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreation"];
            };
        };
        responses: {
            /** @description Message modifié */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
        };
    };
    listCanaux: {
        parameters: {
            query?: {
                /** @description Uniquement les canaux de ce pays */
                pays?: components["schemas"]["Pays"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des canaux */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Canal"][];
                };
            };
        };
    };
    createCanal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanalCreation"];
            };
        };
        responses: {
            /** @description Canal créé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Canal"];
                };
            };
            401: components["responses"]["NonConnecte"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
        };
    };
    listEtiquettes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Les étiquettes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Etiquette"][];
                };
            };
        };
    };
    listCorrectifs: {
        parameters: {
            query?: {
                /** @description Numéro de page (commence à 1) */
                page?: components["parameters"]["Page"];
                /** @description Éléments par page (50 maximum) */
                per_page?: components["parameters"]["ParPage"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des correctifs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data: components["schemas"]["Correctif"][];
                    };
                };
            };
            404: components["responses"]["Introuvable"];
        };
    };
    createCorrectif: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectifCreation"];
            };
        };
        responses: {
            /** @description Correctif proposé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Correctif"];
                };
            };
            401: components["responses"]["NonConnecte"];
            /** @description GitHub non lié au compte */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erreur"];
                };
            };
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
            429: components["responses"]["TropDeRequetes"];
        };
    };
    acceptCorrectif: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Correctif accepté */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Correctif"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["Conflit"];
            419: components["responses"]["CsrfInvalide"];
        };
    };
    deployCorrectif: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Déploiement mis en file ; son état arrive par Reverb */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deploiement"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["Conflit"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
            429: components["responses"]["TropDeRequetes"];
        };
    };
    createMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissionCreation"];
            };
        };
        responses: {
            /** @description Demande envoyée à l'auteur */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            401: components["responses"]["NonConnecte"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
            429: components["responses"]["TropDeRequetes"];
        };
    };
    listMissions: {
        parameters: {
            query?: {
                /** @description Numéro de page (commence à 1) */
                page?: components["parameters"]["Page"];
                /** @description Éléments par page (50 maximum) */
                per_page?: components["parameters"]["ParPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste de mes missions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data: components["schemas"]["Mission"][];
                    };
                };
            };
            401: components["responses"]["NonConnecte"];
        };
    };
    getMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La mission */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
        };
    };
    listMissionMessages: {
        parameters: {
            query?: {
                /** @description Numéro de page (commence à 1) */
                page?: components["parameters"]["Page"];
                /** @description Éléments par page (50 maximum) */
                per_page?: components["parameters"]["ParPage"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data: components["schemas"]["Message"][];
                    };
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
        };
    };
    createMissionMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreation"];
            };
        };
        responses: {
            /** @description Message publié (diffusé sur le canal privé mission.{id}) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /** @description Numéro de page (commence à 1) */
                page?: components["parameters"]["Page"];
                /** @description Éléments par page (50 maximum) */
                per_page?: components["parameters"]["ParPage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des événements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data: components["schemas"]["Evenement"][];
                    };
                };
            };
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvenementCreation"];
            };
        };
        responses: {
            /** @description Événement créé */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evenement"];
                };
            };
            401: components["responses"]["NonConnecte"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description L'événement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evenement"];
                };
            };
            404: components["responses"]["Introuvable"];
        };
    };
    deleteEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Événement supprimé */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvenementModification"];
            };
        };
        responses: {
            /** @description Événement modifié */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evenement"];
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
        };
    };
    registerEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inscrit */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NonConnecte"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["Conflit"];
            419: components["responses"]["CsrfInvalide"];
        };
    };
    unregisterEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Désinscrit */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NonConnecte"];
            404: components["responses"]["Introuvable"];
            419: components["responses"]["CsrfInvalide"];
        };
    };
    listParticipants: {
        parameters: {
            query?: {
                /** @description Numéro de page (commence à 1) */
                page?: components["parameters"]["Page"];
                /** @description Éléments par page (50 maximum) */
                per_page?: components["parameters"]["ParPage"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des participants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data: components["schemas"]["Dev"][];
                    };
                };
            };
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
        };
    };
    listAvis: {
        parameters: {
            query?: {
                /** @description Numéro de page (commence à 1) */
                page?: components["parameters"]["Page"];
                /** @description Éléments par page (50 maximum) */
                per_page?: components["parameters"]["ParPage"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des avis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        data: components["schemas"]["Avis"][];
                    };
                };
            };
            404: components["responses"]["Introuvable"];
        };
    };
    createAvis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvisCreation"];
            };
        };
        responses: {
            /** @description Avis publié */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Avis"];
                };
            };
            401: components["responses"]["NonConnecte"];
            403: components["responses"]["Interdit"];
            404: components["responses"]["Introuvable"];
            409: components["responses"]["Conflit"];
            419: components["responses"]["CsrfInvalide"];
            422: components["responses"]["Invalide"];
        };
    };
}
